{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qqman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qqman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qqman/qqman_{{ version }}.tar.gz
  sha256: 58da8317df8d726d1fde4805919da5d64f880894a423ee20937cafb479b9d8a8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-calibrate
  run:
    - r-base
    - r-calibrate

test:
  commands:
    - $R -e "library('qqman')"           # [not win]
    - "\"%R%\" -e \"library('qqman')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qqman
  license: GPL-3
  summary: Create Q-Q and manhattan plots for GWAS data from PLINK results.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: qqman
# Title: Q-Q and Manhattan Plots for GWAS Data
# Version: 0.1.4
# Author: Stephen Turner <vustephen@gmail.com>
# Maintainer: Stephen Turner <vustephen@gmail.com>
# Description: Create Q-Q and manhattan plots for GWAS data from PLINK results.
# Depends: R (>= 3.0.0),
# Imports: calibrate
# Suggests: knitr
# License: GPL-3
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-03-15 17:42:34 UTC; sdt5z
# Repository: CRAN
# Date/Publication: 2017-03-16 03:19:14
