appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: f/cSTsI2Yp/hgvyghZFsdoN+2Y1dpXGH8XMlcsAJrg0zR0r5nEbiKJH8x73nrSi9VE78XyYC/Tro4W4xFuOiyG2QxsR8O9JVXjKjx08YQLuDekSwocqSMWP39aWmlraSHi97nwfreK69tWiGVB55PTJ/wpJNMRmuem/9VPDX/P4DKCEpAJ/f+jJ45PrrUqgJstW7a3nzRG0fNh6F+L/jtvBLCde6ZBy4dDVaCC4xNZm3srMJIBBUDCEBBM8lkrmhUfJxRRBGMMw5u0SNIbqH3N/Zf7FZnwZB19H6aY9uhv5kTVmkwfR0jXoDZW5gWxb/w00MF2WBDOaIcTYJl3BHm2IF+WNfNDZlE8e0gPY/d2m25YXbJBN606SZGMpbWFjCexftEGxRUt+yJBDHS510Y6pL5biz7zTj5JvPVsVwxgCfFcn6I5qCa5IkzkQodUuBSRbpbFUrTmT5AfOuyUdD5/TaNc1MDUIzrIk9Tb5/ptpS2L2tPnHB03izybf0HsbNHfYlt86+Lr91Zui87FufWIcdSgSaVjT8wVHVYBTUwpo5mDdnVzvJKlxIwzBREo+Y/OG0q7ZF9jXHqZ61xtBqYbBT43NAXT0JGj4J98DaaXnq7IY9jOOdhqgaIQSZfr9CqHsDWW5KJhN7cfgiplBk3ftrlhmMyIlSyx9R8Qd29AA=
